apiVersion: v1
kind: ConfigMap
metadata:
  name: is-skeletons-heatmap
  namespace: default
data:
  options: |-
    {
      "broker_uri": "amqp://rabbitmq.default",
      "zipkin_host": "zipkin.default",
      "zipkin_port": 30200,
      "group_ids": [
        0
      ],
      "limits": {
        "xmin": -4.0,
        "xmax": 4.0,
        "ymin": -4.0,
        "ymax": 4.0
      },
      "bins_step": 0.05,
      "output_scale": 3.0,
      "output_rotate": "NONE",
      "referential": {
        "x": 0.0,
        "y": 0.0,
        "length": 50
      },
      "frame_id": 1000,
      "draw_grid": true,
      "flip_horizontal": false,
      "flip_vertical": true,
      "log_scale": true,
      "average_coordinates": false,
      "samples": 10000,
      "period_ms": 200
    }
