# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roptions.proto\x12\x02is\x1a\x1egoogle/protobuf/wrappers.proto\"D\n\nAreaLimits\x12\x0c\n\x04xmin\x18\x01 \x01(\x02\x12\x0c\n\x04xmax\x18\x02 \x01(\x02\x12\x0c\n\x04ymin\x18\x03 \x01(\x02\x12\x0c\n\x04ymax\x18\x04 \x01(\x02\"=\n\x15ReferentialProperties\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0e\n\x06length\x18\x03 \x01(\r\"\xd1\x03\n\x17SkeletonsHeatmapOptions\x12\x12\n\nbroker_uri\x18\x01 \x01(\t\x12\x13\n\x0bzipkin_host\x18\x02 \x01(\t\x12\x13\n\x0bzipkin_port\x18\x03 \x01(\r\x12\x11\n\tgroup_ids\x18\x04 \x03(\r\x12\x1e\n\x06limits\x18\x05 \x01(\x0b\x32\x0e.is.AreaLimits\x12\x11\n\tbins_step\x18\x06 \x01(\x02\x12\x31\n\x0coutput_scale\x18\x07 \x01(\x0b\x32\x1b.google.protobuf.FloatValue\x12&\n\routput_rotate\x18\x0f \x01(\x0e\x32\x0f.is.RotateFlags\x12\x10\n\x08\x66rame_id\x18\x11 \x01(\x03\x12.\n\x0breferential\x18\x08 \x01(\x0b\x32\x19.is.ReferentialProperties\x12\x11\n\tdraw_grid\x18\t \x01(\x08\x12\x17\n\x0f\x66lip_horizontal\x18\n \x01(\x08\x12\x15\n\rflip_vertical\x18\x0b \x01(\x08\x12\x11\n\tlog_scale\x18\x0c \x01(\x08\x12\x1b\n\x13\x61verage_coordinates\x18\r \x01(\x08\x12\x0f\n\x07samples\x18\x0e \x01(\x05\x12\x11\n\tperiod_ms\x18\x10 \x01(\x05*L\n\x0bRotateFlags\x12\x08\n\x04NONE\x10\x00\x12\x10\n\x0cROTATE_90_CW\x10\x01\x12\x0e\n\nROTATE_180\x10\x02\x12\x11\n\rROTATE_90_CCW\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'options_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ROTATEFLAGS._serialized_start=654
  _ROTATEFLAGS._serialized_end=730
  _AREALIMITS._serialized_start=53
  _AREALIMITS._serialized_end=121
  _REFERENTIALPROPERTIES._serialized_start=123
  _REFERENTIALPROPERTIES._serialized_end=184
  _SKELETONSHEATMAPOPTIONS._serialized_start=187
  _SKELETONSHEATMAPOPTIONS._serialized_end=652
# @@protoc_insertion_point(module_scope)
